version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  AfterInstall:
    - location: install_dependency.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: root